[DBZ-PGYB][yugabyte/yugabyte-db#27253] Change default from USE_SNAPSHOT TO EXPORT_SNAPSHOT (#188)
## Problem
With 2025.2.2 and later branches, we plan to enable EXPORT_SNAPSHOT by
default instead of USE_SNAPSHOT. However, we need to maintain backward
compatibility with old branches where we didn't have EXPORT_SNAPSHOT on
by default and needed a g-flag to be set to true for it to even work.
Otherwise, it ends up throwing the below error.
```
ERROR:  cannot export or import snapshot when ysql_enable_pg_export_snapshot is disabled.
```

Recommended to read
[https://github.com/yugabyte/debezium/pull/113](https://github.com/yugabyte/debezium/pull/113)
for getting a better context of the change.


## Solution

1. Add a variable (`exportSnapshotUsed`) to `SlotCreationResult` which
will tell the connector if the slot was created with EXPORT_SNAPSHOT or
USE_SNAPSHOT.
2. First, to maintain backward compatibility with versions where the
flag `ysql_enable_pg_export_snapshot` was not enabled, we will add a
fallback mechanism.
i. First, the connector will try to create a replication slot by
explicitly mentioning `EXPORT_SNAPSHOT` in the command (or not if
parallel streaming is off). If this fails with an error `cannot export
or import snapshot when ysql_enable_pg_export_snapshot is disabled.`,
then we fallback to the old code of the connector which will create a
replication slot by explicitly mentioning `USE_SNAPSHOT` (or not if
parallel streaming is off).
ii. **Note**: Even if we don't pass anything in the create replication
slot command, it uses the default, which in 2025.2.2 and above versions
is `EXPORT_SNAPSHOT` and in 2025.2.1 and below versions is
`USE_SNAPSHOT`.
3. When a new replication slot is created, we store all the data in
`slotCreatedInfo` including whether EXPORT_SNAPSHOT was used.
i. For versions where `EXPORT_SNAPSHOT` is enabled,
`slotCreatedInfo.isExportSnapshotUsed()` will be `true` and
snapshot_name will be the snapshot ID.
```
yugabyte=# CREATE_REPLICATION_SLOT test_replication_slot_99d2fc58624f4aa29f1317d434e LOGICAL pgoutput;
                     slot_name                     | consistent_point |                           snapshot_name                           | output_plugin 
---------------------------------------------------+------------------+-------------------------------------------------------------------+---------------
 test_replication_slot_99d2fc58624f4aa29f1317d434e | 0/2              | e928c3c6c4d54deca3c449dae1e00233-ae0666b99cc6d3be93494b0d1022eb8f | pgoutput
```
and then use this snapshot ID to set it in the snapshot session:
```
String setSnapshotQuery = "SET TRANSACTION SNAPSHOT '" + slotCreatedInfo.snapshotName() + "';";
jdbcConnection.executeWithoutCommitting(setSnapshotQuery);
```


ii. For versions where `EXPORT_SNAPSHOT` is **not** enabled,
snapshot_name will be the hybrid time.
```
yugabyte=# CREATE_REPLICATION_SLOT test_replication_slot_99d2fc58624f4aa29f1317d434e4831c LOGICAL pgoutput;
                       slot_name                        | consistent_point |    snapshot_name    | output_plugin 
--------------------------------------------------------+------------------+---------------------+---------------
 test_replication_slot_99d2fc58624f4aa29f1317d434e4831c | 0/2              | 7227389791448002560 | pgoutput
```

and then we use this hybrid time to set the local read time of the
snapshot session (Note: This is pre-existing code):
```
private String ybSnapshotStatement(String ybReadTime) {
        return String.format("DO " +
                             "LANGUAGE plpgsql $$ " +
                             "BEGIN " +
                                "SET LOCAL yb_read_time TO '%s ht'; "  +
                             "EXCEPTION " +
                                "WHEN OTHERS THEN " +
                                    "CALL set_yb_read_time('%s ht'); " +
                             "END $$;",
                             ybReadTime, ybReadTime);
    }
```

4. For connector restart case:
i. If the slot is re-created (parallel streaming mode drops and
recreates the slot on mid-snapshot restart): Steps 1, 2 & 3 will be
repeated.
    ii. If the slot already exists (slotCreatedInfo is null):
a. For EXPORT_SNAPSHOT, we cannot use the old snapshot ID as the moment
the session closes, the snapshot is deleted, and when the connector is
restarted, there is no way to access it. So for this case, we will
fallback to the old code where we set the hybrid time from the slot
(`slotState.slotRestartCommitHT()`) as the local read time.
 


## Test Plan

```

./mvnw test -pl debezium-connector-postgres -Dtest="PostgresConnectorIT#shouldStreamWithExportSnapshotDisabledAndPreCreatedSlotWithUseSnapshot,PostgresConnectorIT#shouldStreamWithDefaultFlagsAndConnectorCreatedSlot,PostgresConnectorIT#shouldStreamWithDefaultFlagsAndPreCreatedSlotViaReplicationConnection"
```